/**
	hsmCommunicator.c

	This file automatically generated by FSMLang
*/

#include "hsmCommunicator.h"

const HSM_COMMUNICATOR_ACTION_TRANS hsmCommunicator_action_array[hsmCommunicator_numEvents][hsmCommunicator_numStates] =
{
	{
		/* -- SEND_MESSAGE -- */

		/* -- IDLE -- */	{hsmCommunicator_startSessionEstablishment,hsmCommunicator_ESTABLISHING_SESSION}
		/* -- ESTABLISHING_SESSION -- */	, {hsmCommunicator_requestMessageTransmission,hsmCommunicator_ESTABLISHING_SESSION}
		/* -- IN_SESSION -- */	, {hsmCommunicator_requestMessageTransmission,hsmCommunicator_IN_SESSION}
	},
	{
		/* -- SESSION_ESTABLISHED -- */

		/* -- IDLE -- */	{hsmCommunicator_noAction, hsmCommunicator_IDLE}
		/* -- ESTABLISHING_SESSION -- */	, {hsmCommunicator_completeSessionStart,hsmCommunicator_IN_SESSION}
		/* -- IN_SESSION -- */	, {hsmCommunicator_noAction, hsmCommunicator_IN_SESSION}
	},
	{
		/* -- SESSION_TIMEOUT -- */

		/* -- IDLE -- */	{hsmCommunicator_noAction, hsmCommunicator_IDLE}
		/* -- ESTABLISHING_SESSION -- */	, {hsmCommunicator_notifySessionTimeout,hsmCommunicator_IDLE}
		/* -- IN_SESSION -- */	, {hsmCommunicator_notifySessionTimeout,hsmCommunicator_IDLE}
	},
};

pHSM_COMMUNICATOR_SUB_FSM_IF hsmCommunicator_sub_fsm_if_array[hsmCommunicator_numSubMachines] =
{
	&establishSession_sub_fsm_if
	, &sendMessage_sub_fsm_if
};

HSM_COMMUNICATOR hsmCommunicator = {
	hsmCommunicator_IDLE,
	&hsmCommunicator_action_array,
	&hsmCommunicator_sub_fsm_if_array,
	hsmCommunicatorFSM
};

pHSM_COMMUNICATOR phsmCommunicator = &hsmCommunicator;

static HSM_COMMUNICATOR_EVENT findAndRunSubMachine(pHSM_COMMUNICATOR, HSM_COMMUNICATOR_EVENT);

void hsmCommunicatorFSM(pHSM_COMMUNICATOR pfsm, HSM_COMMUNICATOR_EVENT event)
{
/* writeOriginalFSM */
	HSM_COMMUNICATOR_EVENT new_e;

	HSM_COMMUNICATOR_EVENT e = event;

	while (e != hsmCommunicator_noEvent) {

#ifdef HSM_COMMUNICATOR_DEBUG
DBG_PRINTF("event: %s; state: %s"
,HSM_COMMUNICATOR_EVENT_NAMES[e]
,HSM_COMMUNICATOR_STATE_NAMES[pfsm->state]
);
#endif

		if (e < hsmCommunicator_noEvent)
		{

			new_e = ((* (*pfsm->actionArray)[e][pfsm->state].action)(pfsm));

			pfsm->state = (*pfsm->actionArray)[e][pfsm->state].transition;

			e = new_e;

		} 
		else
		{
			e = findAndRunSubMachine(pfsm, e);
		}

	}

}


static HSM_COMMUNICATOR_EVENT findAndRunSubMachine(pHSM_COMMUNICATOR pfsm, HSM_COMMUNICATOR_EVENT e)
{
	for (HSM_COMMUNICATOR_SUB_MACHINES machineIterator = hsmCommunicator_firstSubMachine;
	     machineIterator < hsmCommunicator_numSubMachines;
	     machineIterator++
	    )
	{
			if (
			   ((*pfsm->subMachineArray)[machineIterator]->first_event <= e)
			   && ((*pfsm->subMachineArray)[machineIterator]->last_event >= e)
			    )
			{
				return ((*(*pfsm->subMachineArray)[machineIterator]->subFSM)(e));
			}
	}

	return hsmCommunicator_noEvent;

}

HSM_COMMUNICATOR_EVENT __attribute__((weak)) hsmCommunicator_startSessionEstablishment(pHSM_COMMUNICATOR pfsm)
{
	DBG_PRINTF("weak: hsmCommunicator_startSessionEstablishment");
	return THIS(noEvent);
}

HSM_COMMUNICATOR_EVENT __attribute__((weak)) hsmCommunicator_completeSessionStart(pHSM_COMMUNICATOR pfsm)
{
	DBG_PRINTF("weak: hsmCommunicator_completeSessionStart");
	return THIS(noEvent);
}

HSM_COMMUNICATOR_EVENT __attribute__((weak)) hsmCommunicator_notifySessionTimeout(pHSM_COMMUNICATOR pfsm)
{
	DBG_PRINTF("weak: hsmCommunicator_notifySessionTimeout");
	return THIS(noEvent);
}

HSM_COMMUNICATOR_EVENT __attribute__((weak)) hsmCommunicator_requestMessageTransmission(pHSM_COMMUNICATOR pfsm)
{
	DBG_PRINTF("weak: hsmCommunicator_requestMessageTransmission");
	return THIS(noEvent);
}

HSM_COMMUNICATOR_EVENT __attribute__((weak)) hsmCommunicator_noAction(pHSM_COMMUNICATOR pfsm)
{
	DBG_PRINTF("weak: hsmCommunicator_noAction");
	return hsmCommunicator_noEvent;
}


#ifdef HSM_COMMUNICATOR_DEBUG
char *HSM_COMMUNICATOR_EVENT_NAMES[] = {
	 "hsmCommunicator_SEND_MESSAGE"
	, "hsmCommunicator_SESSION_ESTABLISHED"
	, "hsmCommunicator_SESSION_TIMEOUT"
	, "hsmCommunicator_noEvent"
	, "hsmCommunicator_numEvents"
	, "hsmCommunicator_establishSession_ESTABLISH_SESSION_REQUEST"
	, "hsmCommunicator_establishSession_STEP0_RESPONSE"
	, "hsmCommunicator_establishSession_STEP1_RESPONSE"
	, "hsmCommunicator_establishSession_noEvent"
	, "hsmCommunicator_sendMessage_SEND_MESSAGE"
	, "hsmCommunicator_sendMessage_ACK"
	, "hsmCommunicator_sendMessage_SESSION_ESTABLISHED"
	, "hsmCommunicator_sendMessage_SESSION_TIMEOUT"
	, "hsmCommunicator_sendMessage_noEvent"
};

char *HSM_COMMUNICATOR_STATE_NAMES[] = {
	 "hsmCommunicator_IDLE"
	,"hsmCommunicator_ESTABLISHING_SESSION"
	,"hsmCommunicator_IN_SESSION"
};

#endif
