/**
	simpleCommunicator.h

	This file automatically generated by FSMLang
*/

#ifndef _SIMPLECOMMUNICATOR_H_
#define _SIMPLECOMMUNICATOR_H_

#include "simpleCommunicator_events.h"
#define FSM_VERSION "1.45.1"

#ifndef NO_CONVENIENCE_MACROS
#undef UFMN
#define UFMN(A) simpleCommunicator_##A
#undef THIS
#define THIS(A) simpleCommunicator_##A
#endif
#undef STATE
#define STATE(A) simpleCommunicator_##A

#undef ACTION_RETURN_TYPE
#define ACTION_RETURN_TYPE SIMPLE_COMMUNICATOR_EVENT

void run_simpleCommunicator(SIMPLE_COMMUNICATOR_EVENT);

typedef struct _simpleCommunicator_struct_ *pSIMPLE_COMMUNICATOR;
extern pSIMPLE_COMMUNICATOR psimpleCommunicator;


#endif
