/**
	simpleCommunicator.h

	This file automatically generated by FSMLang
*/

#ifndef _SIMPLECOMMUNICATOR_H_
#define _SIMPLECOMMUNICATOR_H_

#include "simpleCommunicator_events.h"
#ifndef SIMPLE_COMMUNICATOR_NATIVE_PROLOG
#define SIMPLE_COMMUNICATOR_NATIVE_PROLOG

#include <stdio.h>
#define DBG_PRINTF(...) printf(__VA_ARGS__); printf("\n")

#endif
#define FSM_VERSION "2.2.2"

#ifndef NO_CONVENIENCE_MACROS
#undef UFMN
#define UFMN(A) simpleCommunicator_##A
#undef THIS
#define THIS(A) simpleCommunicator_##A
#undef STATE
#define STATE(A) simpleCommunicator_##A
#undef ACTION_RETURN_TYPE
#define ACTION_RETURN_TYPE SIMPLE_COMMUNICATOR_EVENT
#undef DECLARE_TR_FN_RET_VAR
#define DECLARE_TR_FN_RET_VAR(A, B) SIMPLE_COMMUNICATOR_STATE A = STATE(B)
#undef RETURN_STATE
#define RETURN_STATE(A, B) A = STATE(B)
#undef TR_FN_RETURN_TYPE
#define TR_FN_RETURN_TYPE SIMPLE_COMMUNICATOR_STATE
#endif

typedef enum {
	  simpleCommunicator_instance_0
	, simpleCommunicator_numInstances
} SIMPLE_COMMUNICATOR_INSTANCE;



void run_simpleCommunicator(SIMPLE_COMMUNICATOR_EVENT);

typedef struct _simpleCommunicator_struct_ *pSIMPLE_COMMUNICATOR;
extern pSIMPLE_COMMUNICATOR psimpleCommunicator;


#endif
