/**
	simpleCommunicator_events.h

	This file automatically generated by FSMLang
*/

#ifndef _SIMPLECOMMUNICATOR_EVENTS_H_
#define _SIMPLECOMMUNICATOR_EVENTS_H_

#ifndef SIMPLE_COMMUNICATOR_NATIVE_PROLOG
#define SIMPLE_COMMUNICATOR_NATIVE_PROLOG

#include <stdio.h>
#define DBG_PRINTF(...) printf(__VA_ARGS__); printf("\n")

#endif
typedef enum SIMPLE_COMMUNICATOR_EVENT {
	 simpleCommunicator_SEND_MESSAGE
	, simpleCommunicator_NEVER_SEEN
	, simpleCommunicator_ACK
	, simpleCommunicator_noEvent
	, simpleCommunicator_numEvents
	, simpleCommunicator_numAllEvents = simpleCommunicator_numEvents
}  SIMPLE_COMMUNICATOR_EVENT;


#endif
